/*
* Generated by muaohua
* Created on Sun May 14 2017 17:31:13 GMT+0800 (+08)
* Awesome work!
*/

import React, { Component } from 'react';

import styles from './styles.css';

import Button from '../../components/Button';

class StyleGuide extends Component {
  render() {
    return (
      <div className={styles.container}>
        <div>
          <h1>Button</h1>
          <Button>
            submit
          </Button>
          <Button disabled>
            disabled
          </Button>
        </div>
      </div>
    );
  }
}

export default StyleGuide;
