/*
* Generated by muaohua
* Created on Sun May 14 2017 17:31:13 GMT+0800 (+08)
* Awesome work!
*/

import React from 'react';
/* eslint import/no-extraneous-dependencies: ["error", {"devDependencies": true}] */
import renderer from 'react-test-renderer';

import StyleGuide from '../index';

/* global test:true expect:true */
test('StyleGuide renders correctly', () => {
  const component = renderer.create(
    <StyleGuide />
  );
  const tree = component.toJSON();
  expect(tree).toMatchSnapshot();
});
