/*
* Generated by muaohua
* Created on Tue May 30 2017 15:54:15 GMT+0800 (+08)
* Awesome work!
*/

import React from 'react';
import PropTypes from 'prop-types';
import ProgressBar from 'react-toolbox/lib/progress_bar';

import styles from './styles.css';

function Loader(props) {
  const className = props.className ? `${styles.loader} ${props.className}` : styles.loader;

  return (
    <div className={`${className}`}>
      <ProgressBar type="circular" mode="indeterminate" multicolor />
    </div>
  );
}

Loader.propTypes = {
  className: PropTypes.string,
};

export default Loader;
