/*
* Generated by muaohua
* Created on Tue May 30 2017 15:54:15 GMT+0800 (+08)
* Awesome work!
*/

import React from 'react';
/* eslint import/no-extraneous-dependencies: ["error", {"devDependencies": true}] */
import renderer from 'react-test-renderer';

import Loader from '../index';

/* global test:true expect:true */
test('Loader renders correctly', () => {
  const component = renderer.create(
    <Loader>Facebook</Loader>
  );
  const tree = component.toJSON();
  expect(tree).toMatchSnapshot();
});
