const fs = require('fs');

function generateContainer(dir, name) {
  fs.mkdirSync(`${dir}/tests`);

  // component templete
  const basicContainer = `/*
* Generated by ${process.env.USER}
* Created on ${new Date()}
* Awesome work!
*/

import React, { Component } from 'react';

import styles from './styles.css';

class ${name} extends Component {

  // react component lifecycle, please remove the one not needed.
  constructor(props) {
    super(props);
  }

  componentWillMount() {

  }

  componentDidMount() {

  }

  componentWillReceiveProps(nextProps) {

  }

  shouldComponentUpdate(nextProps, nextState) {

  }

  componentWillUpdate(nextProps, nextState) {

  }

  componentDidUpdate(prevProps, prevState) {

  }

  render() {
    return (
      <div>React-simple-starter-kit</div>
    );
  }
}

export default ${name};
`;

  // style templete
  const basicStyle = `/*
* Generated by ${process.env.USER}
* Created on ${new Date()}
* Awesome work!
* create your ${name} container component's scss here
*/
`;

  // test templete
  const basicTest = `/*
* Generated by ${process.env.USER}
* Created on ${new Date()}
* Awesome work!
*/

import React from 'react';
/* eslint import/no-extraneous-dependencies: ["error", {"devDependencies": true}] */
import renderer from 'react-test-renderer';

import ${name} from '../index';

/* global test:true expect:true */
test('${name} renders correctly', () => {
  const component = renderer.create(
    <${name} />
  );
  const tree = component.toJSON();
  expect(tree).toMatchSnapshot();
});
`;

  // generate component
  fs.writeFile(`${dir}/index.js`, basicContainer, (err) => {
    if (err) {
      console.error('Error in generating container %s. Deleting files...', err);
      fs.rmdirSync(dir);
    } else {
      console.info('generated file index.js in %s.', dir);
    }
  });

  // generate style
  fs.writeFile(`${dir}/styles.css`, basicStyle, (err) => {
    if (err) {
      console.error('Error in generating style %s. Deleting files...', err);
      fs.rmdirSync(dir);
    } else {
      console.info('generated file styles.css in %s.', dir);
    }
  });

  // generate test
  fs.writeFile(`${dir}/tests/index.test.js`, basicTest, (err) => {
    if (err) {
      console.error('Error in generating tests %s. Deleting files...', err);
      fs.rmdirSync(dir);
    } else {
      console.info('generated file index.test.js in %s.', `${dir}/tests`);
    }
  });
}

module.exports = generateContainer;
