/*
* Generated by muaohua
* Created on Tue May 30 2017 10:22:11 GMT+0800 (+08)
* Awesome work!
*/

import React from 'react';
/* eslint import/no-extraneous-dependencies: ["error", {"devDependencies": true}] */
import renderer from 'react-test-renderer';

import Input from '../index';

/* global test:true expect:true */
test('Input renders correctly', () => {
  const component = renderer.create(
    <Input>Facebook</Input>
  );
  const tree = component.toJSON();
  expect(tree).toMatchSnapshot();
});
