/*
* Generated by muaohua
* Created on Sun May 14 2017 18:26:38 GMT+0800 (+08)
* Awesome work!
*/

import React, { Children } from 'react';
import PropTypes from 'prop-types';

import styles from './styles.css';

function TextInput(props) {
  const className = props.className ? `${props.className} ${styles.textInput}` : styles.textInput;

  return (
    <div className={`${className}`}>
      {Children.toArray(props.children)}
    </div>
  );
}

TextInput.propTypes = {
  className: PropTypes.string,
  children: PropTypes.node.isRequired,
};

export default TextInput;
