/*
* Generated by muaohua
* Created on Tue May 30 2017 10:22:11 GMT+0800 (+08)
* Awesome work!
*/

import React from 'react';
import PropTypes from 'prop-types';
import Input from 'react-toolbox/lib/input';

import styles from './styles.css';

function input(props) {
  const className = props.className ? `${styles.input} ${props.className}` : styles.input;
  const { label, type, value, onChange } = props;

  return (
    <Input type={type || 'text'} label={label || ''} value={value} onChange={onChange} className={className} />
  );
}

input.propTypes = {
  className: PropTypes.string,
  label: PropTypes.string,
  type: PropTypes.string,
  value: PropTypes.string,
  onChange: PropTypes.func,
};

export default input;
